### ISSUE TITLE
Ember 3.24: installing ember-cli-flash throws error from ember-cli-version-checker

### ISSUE THREAD

**Issue by NullVoxPopuli** [poteto/ember-cli-flash#347] opened 2021-01-28 15:24 UTC
```
 ember install ember-cli-flash
⠋ Installing addon package

🚧  Installing packages... This might take a couple of minutes.
npm: Installed ember-cli-flash
installing ember-cli-flash
  create tests/helpers/flash-message.js
[ember-cli-version-checker] 'checker.forEmber' has been removed, please use 'checker.for(`ember-source`)'

Stack Trace and Error Report: /tmp/error.dump.c6db452dbe1dfda10b5fdac95d9573bd.log

```

and the part of that log that's relevant (afaict):
```
  - stack: Error: [ember-cli-version-checker] 'checker.forEmber' has been removed, please use 'checker.for(`ember-source`)'
    at VersionChecker.forEmber (/.../ec-flash-typescript-repro/node_modules/ember-cli-version-checker/src/version-checker.js:26:11)
    at Class.afterInstall (/.../ec-flash-typescript-repro/node_modules/ember-cli-flash/blueprints/ember-cli-flash/index.js:14:25)
```

**Comment by lolmaus** [comment] 2021-01-29 08:21
Duplicate of #340.

**Closed** 2021-02-26 17:10 UTC
